title: Data Science with Python
author: 
copyright: "2021"
logo: mvlogo.png

execute:
  execute_notebooks: "cache"
  timeout: 7200 

parse:
  myst_extended_syntax: true
  myst_enable_extensions:
    # https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    # https://github.com/executablebooks/jupyter-book/blob/c923bdbfb178d3da478394d6149a7754034ed6fb/docs/_config.yml
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution

sphinx:
  extra_extensions: [sphinx_multitoc_numbering, sphinxext.rediraffe, sphinx_tojupyter, sphinx_thebe, sphinx_inline_tabs, sphinx-prompt]
  config:
    nb_render_priority:
      html:
      - "application/vnd.jupyter.widget-view+json"
      - "application/javascript"
      - "text/html"
      - "text/latex"
      - "image/svg+xml"
      - "image/png"
      - "image/jpeg"
      - "text/markdown"
      - "text/plain"
      jupyter:
      - "application/vnd.jupyter.widget-view+json"
      - "application/javascript"
      - "text/html"
      - "text/latex"
      - "image/svg+xml"
      - "image/png"
      - "image/jpeg"
      - "text/markdown"
      - "text/plain"
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    html_theme: quantecon_book_theme
    html_static_path: ['_static']

    html_theme_options:
      header_organisation_url: https://community.multiverse.io/
      header_organisation: Multiverse
      repository_url: https://github.com/communitylab/data
      repository_branch: main
      nb_repository_url: https://github.com/communitylab/data
      og_logo_url: https://raw.githubusercontent.com/Ashray-shetty/bookcopy/main/Multiverse_Logo_RGB_Indigo-02.png
      persistent_sidebar: true
      launch_buttons:
        colab_url: https://colab.research.google.com
        binderhub_url: https://mybinder.org
        thebe: True

    tojupyter_static_file_path: ["source/_static", "_static"]
    tojupyter_target_html: true
    tojupyter_urlpath: "https://github.com/communitylab/data"
    tojupyter_image_urlpath: "https://github.com/communitylab/data"
    tojupyter_lang_synonyms: ["ipython", "ipython3", "python"]
    tojupyter_kernels:
      python3:
        kernelspec:
          display_name: "Python"
          language: python3
          name: python3
        file_extension: ".py"
    tojupyter_images_markdown: true



html:
  favicon: mvlogo.png
  navbar_footer_text: Visit our <a href="https://github.com/MultiverseDF/book">repository</a>



repository:
  url: https://github.com/communitylab/data                   
  path_to_book: .                  
  branch: main

