# Name your workflow so you can tell them apart!
 name: deploy-book

 # The workflow will only run when the master branch changes
 on:
   push:
     branches:
       - main
   pull_request:
     branches:
       - main

 jobs:
   # This job installs dependencies, builds the book, and pushes it to `gh-pages`
   deploy-book:
     runs-on: ubuntu-latest  # We request a Linux machine to run the job
     steps:
       # We need to check out the repository. The step uses an Action written
       # by the GitHub Actions team
       - name: Checkout repo
         uses: actions/checkout@v2

       # Install Python using another Action
       - name: Set up Python 3.8
         uses: actions/setup-python@v1
         with:
           python-version: 3.8

       # Install the book dependencies
       - name: Install dependencies
         run: |
           pip install -r requirements.txt
       # Build the book
       - name: Build the book
         run: |
           jupyter-book build .
       
       - name: Run html proofer
         uses: chabad360/htmlproofer@master
         with:
           directory: "./_build/html"
           arguments: --assume-extension --disable-external --only_4xx
         continue-on-error: true

       # Push the book's HTML to github-pages
       - name: GitHub Pages action
         if: github.event_name == 'push' && github.ref == 'refs/heads/main'
         uses: peaceiris/actions-gh-pages@v3.6.1
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}  # This token is automatically generated, don't worry about adding it
           publish_dir: ./_build/html
